include $(THEOS_MAKE_PATH)/common.mk

BUNDLE_NAME := SDSettings
SDSettings_INSTALL_PATH = /Library/PreferenceBundles
SDSettings_BUNDLE_NAME = SafariDownloaderSettings

include $(THEOS_MAKE_PATH)/bundle.mk
